"""simulation.py — Simulation engine, performance metrics, and study runners.

This module is the integration layer between the physical model (auv_model.py)
and the controllers (controllers.py).  It provides:

  simulate()            — main closed-loop simulation (single run)
  compute_metrics()     — derive scalar performance metrics from simulation output
  run_sensitivity()     — sweep T_f and allocation-mismatch δ
  run_generalization()  — multi-scenario + Monte Carlo robustness study
  run_extended_mc()     — 200-run extended Monte Carlo with Wilcoxon tests
"""

from __future__ import annotations

import numpy as np
try:
    from scipy import stats as sp_stats
    _SCIPY_AVAILABLE = True
except Exception:
    _SCIPY_AVAILABLE = False

from auv_model import (
    INERTIA, INERTIA_INV, G_NOM,
    U_MIN, U_MAX, ACTUATOR_TAU, SIGMA_OMEGA_DEFAULT,
    SCENARIOS, GENERALIZATION_SCENARIOS,
    make_g_actual, cross_term, clip_norm,
    allocate_torque, get_reference, disturbance_profile,
    max_available_torque_norm,
)
from controllers import (
    controller_tau_ref,
    adrc_outer_loop, adrc_eso_update,
    init_adrc_state,
    ADRC_OMEGA_O, ADRC_OMEGA_C,
)

# ── Time grid ──────────────────────────────────────────────────────────────────
DT    = 0.01       # sampling interval [s]
T_END = 20.0       # simulation duration [s]
TIME  = np.arange(0.0, T_END + DT, DT)
DEG   = 180.0 / np.pi

T_FILTER_DEFAULT = 0.05   # default observer low-pass filter time constant [s]

MONTE_CARLO_CONTROLLERS = ["proposed", "adrc", "smc", "lqr", "pid"]


# ── Main simulation ────────────────────────────────────────────────────────────
def simulate(
    controller: str,
    case: str,
    tf: float = T_FILTER_DEFAULT,
    mismatch_pct: float = 0.10,
    scenario: str = "nominal",
    rng: np.random.Generator | None = None,
    initial_eta: np.ndarray | None = None,
    sigma_omega: float = SIGMA_OMEGA_DEFAULT,
    freq_scale: float = 1.0,
    dist_onset: float = 8.0,
    gain_scale: dict | None = None,
) -> dict[str, np.ndarray]:
    """Run a single closed-loop simulation of the AUV attitude-control system.

    Fair-comparison protocol
    ────────────────────────
    All controllers use G_NOM for control allocation.  The true plant torque is
    generated by make_g_actual(mismatch_pct), which is identical for every
    controller, so no method has an informational advantage at the allocation
    layer.

    Observer IMU pipeline (proposed variants)
    ─────────────────────────────────────────
    1. Corrupt true ω with zero-mean Gaussian noise (std = sigma_omega).
    2. Finite-difference raw angular-acceleration estimate.
    3. First-order low-pass filter with time constant tf.
    The observer NEVER accesses the true ω_dot.

    Parameters
    ----------
    controller  : one of 'proposed', 'adrc', 'smc', 'lqr', 'pid',
                  'proposed_no_observer', 'proposed_no_smooth'
    case        : 'step' | 'disturbance' | 'combined' | 'sinusoidal_dist'
    tf          : observer low-pass filter time constant [s]
    mismatch_pct: allocation-matrix mismatch level (0.10 = 10 %)
    scenario    : key into SCENARIOS (confined-environment configuration)
    rng         : numpy Generator for reproducible noise; defaults to seed 42
    initial_eta : initial Euler angles [rad]; defaults to zeros
    sigma_omega : IMU gyro noise standard deviation [rad/s]
    freq_scale  : disturbance frequency scaling factor
    dist_onset  : time at which the jet disturbance is injected [s]
    gain_scale  : dict of multiplicative gain scaling for proposed controller

    Returns
    -------
    dict with keys:
        time         : time vector  (N,)
        eta          : Euler angles  (N, 3)  [rad]
        eta_ref      : reference  (N, 3)  [rad]
        omega        : body angular velocity  (N, 3)  [rad/s]
        tau          : true plant torque  (N, 3)  [N·m]
        tau_nom      : nominal torque G_NOM @ u  (N, 3)  [N·m]
        tau_dist     : external disturbance torque  (N, 3)  [N·m]
        u            : fin commands  (N, 4)
        d_hat        : observer estimate of lumped disturbance  (N, 3)
        d_true       : true lumped disturbance acceleration  (N, 3)
        alloc_residual : τ_actual − τ_nom  (N, 3)  [N·m]
        surface      : sliding surface / error signal  (N, 3)
    """
    g_actual = make_g_actual(mismatch_pct)
    rng = np.random.default_rng(42) if rng is None else rng

    # ── State initialisation ──────────────────────────────────────────────────
    eta   = np.zeros(3) if initial_eta is None else np.array(initial_eta, dtype=float)
    omega = np.zeros(3)
    integ = np.zeros(3)
    d_hat = np.zeros(3)
    u     = np.zeros(4)
    u_prev = np.zeros(4)

    # IMU pipeline state
    omega_prev_meas     = np.zeros(3)
    omega_dot_filtered  = np.zeros(3)
    alpha_f = DT / (tf + DT)            # first-order IIR coefficient

    # ADRC ESO state
    adrc_z = init_adrc_state()

    smooth_weight = 0.0 if controller == "proposed_no_smooth" else 0.06

    # ── Storage ───────────────────────────────────────────────────────────────
    etas, refs, omegas       = [], [], []
    torques, tau_noms        = [], []
    disturbances             = []
    fin_cmds                 = []
    d_hats, d_trues          = [], []
    alloc_residuals, surfaces = [], []

    # ── Time loop ─────────────────────────────────────────────────────────────
    for k, t in enumerate(TIME):

        # Reference
        eta_ref, eta_ref_dot, eta_ref_ddot = get_reference(case, t)

        # Integrator (anti-wind-up clip)
        integ += clip_norm(eta - eta_ref, 0.6) * DT

        # ── Noisy IMU measurement ─────────────────────────────────────────────
        omega_meas = omega + rng.normal(0.0, sigma_omega, size=3)

        if k > 0:
            omega_dot_raw = (omega_meas - omega_prev_meas) / DT
        else:
            omega_dot_raw = np.zeros(3)
        omega_dot_filtered = ((1.0 - alpha_f) * omega_dot_filtered
                              + alpha_f * omega_dot_raw)
        omega_prev_meas = omega_meas.copy()

        # ── Outer-loop controller ─────────────────────────────────────────────
        if controller == "adrc":
            tau_ref = adrc_outer_loop(eta, eta_ref, eta_ref_dot, adrc_z)
            surface = eta - eta_ref
        else:
            tau_ref, surface = controller_tau_ref(
                controller, eta, omega, integ, d_hat,
                eta_ref, eta_ref_dot, eta_ref_ddot,
                gain_scale=gain_scale,
            )

        tau_ref = clip_norm(tau_ref, 2.2)

        # ── Inner-loop: allocation (all controllers use G_NOM) ────────────────
        u_cmd = allocate_torque(tau_ref, u_prev, 0.08, smooth_weight, G_NOM)
        # First-order actuator dynamics
        u += (u_cmd - u) * DT / ACTUATOR_TAU
        u  = np.clip(u, U_MIN, U_MAX)

        # ── True plant response ───────────────────────────────────────────────
        tau_nom      = G_NOM    @ u     # what the controller assumed
        tau_control  = g_actual @ u     # what the plant actually generated
        tau_dist     = disturbance_profile(
            t, eta, omega, case, scenario,
            freq_scale=freq_scale, dist_onset=dist_onset,
        )

        # True lumped disturbance acceleration (τ_dist + allocation residual)
        alloc_res = tau_control - tau_nom
        d_true    = INERTIA_INV @ (tau_dist + alloc_res)

        # Equations of motion (reduced-order: η̇ ≈ ω)
        omega_dot = INERTIA_INV @ (tau_control + tau_dist - np.cross(omega, INERTIA @ omega))
        eta_dot   = omega

        # ── Disturbance observer update (proposed variants) ───────────────────
        if controller in {"proposed", "proposed_no_smooth"}:
            omega_dot_nom = INERTIA_INV @ (tau_nom - np.cross(omega_meas, INERTIA @ omega_meas))
            innovation    = omega_dot_filtered - omega_dot_nom
            obs_scale = (gain_scale or {}).get("obs_scale", 1.0)
            L = np.diag([4.5, 4.0, 4.0]) * obs_scale
            d_hat += DT * (L @ (innovation - d_hat))

        # ── ADRC ESO update ───────────────────────────────────────────────────
        if controller == "adrc":
            adrc_eso_update(adrc_z, omega_meas, tau_nom, DT)

        # ── Euler integration ─────────────────────────────────────────────────
        eta   += eta_dot   * DT
        omega += omega_dot * DT
        u_prev = u.copy()

        # ── Record ────────────────────────────────────────────────────────────
        etas.append(eta.copy())
        refs.append(eta_ref.copy())
        omegas.append(omega.copy())
        torques.append(tau_control.copy())
        tau_noms.append(tau_nom.copy())
        disturbances.append(tau_dist.copy())
        fin_cmds.append(u.copy())
        d_hats.append(d_hat.copy())
        d_trues.append(d_true.copy())
        alloc_residuals.append(alloc_res.copy())
        surfaces.append(surface.copy())

    return {
        "time":           TIME.copy(),
        "eta":            np.asarray(etas),
        "eta_ref":        np.asarray(refs),
        "omega":          np.asarray(omegas),
        "tau":            np.asarray(torques),
        "tau_nom":        np.asarray(tau_noms),
        "tau_dist":       np.asarray(disturbances),
        "u":              np.asarray(fin_cmds),
        "d_hat":          np.asarray(d_hats),
        "d_true":         np.asarray(d_trues),
        "alloc_residual": np.asarray(alloc_residuals),
        "surface":        np.asarray(surfaces),
    }


# ── Performance metrics ────────────────────────────────────────────────────────
def settling_time(
    time: np.ndarray,
    signal: np.ndarray,
    target: float,
    start_time: float,
) -> float:
    """First time after start_time at which the signal stays within 2 % of target."""
    start_idx = np.searchsorted(time, start_time)
    if abs(target) < 1e-6:
        return 0.0
    band = 0.02 * abs(target)
    for idx in range(start_idx, len(time)):
        if np.all(np.abs(signal[idx:] - target) <= band):
            return float(time[idx] - start_time)
    return float(time[-1] - start_time)


def overshoot(signal: np.ndarray, target: float, start_idx: int) -> float:
    """Percentage overshoot of signal relative to target."""
    if abs(target) < 1e-6:
        return 0.0
    peak = np.max(signal[start_idx:])
    return float(max(0.0, (peak - target) / abs(target) * 100.0))


def rms_error_deg(
    eta: np.ndarray, eta_ref: np.ndarray, start_idx: int
) -> float:
    """Root-mean-square attitude-error norm [degrees]."""
    err = (eta[start_idx:] - eta_ref[start_idx:]) * DEG
    return float(np.sqrt(np.mean(np.sum(err ** 2, axis=1) / err.shape[1])))


def max_error_deg(
    eta: np.ndarray, eta_ref: np.ndarray, start_idx: int
) -> float:
    """Maximum element-wise attitude error [degrees]."""
    err = np.abs((eta[start_idx:] - eta_ref[start_idx:]) * DEG)
    return float(np.max(err))


def per_axis_rms_deg(
    eta: np.ndarray, eta_ref: np.ndarray, start_idx: int
) -> list[float]:
    """Per-axis RMS error [roll, pitch, yaw] in degrees."""
    err = (eta[start_idx:] - eta_ref[start_idx:]) * DEG
    return [float(np.sqrt(np.mean(err[:, i] ** 2))) for i in range(3)]


def control_variation(u: np.ndarray) -> float:
    """Mean norm of consecutive fin-command differences."""
    return float(np.mean(np.linalg.norm(np.diff(u, axis=0), axis=1)))


def peak_command_rate(u: np.ndarray) -> float:
    """99th-percentile norm of consecutive fin-command differences."""
    return float(np.percentile(np.linalg.norm(np.diff(u, axis=0), axis=1), 99))


def integrated_squared_torque(tau: np.ndarray) -> float:
    """IST = ∫ ‖τ_c(t)‖² dt  [N²·m²·s]."""
    return float(np.sum(np.sum(tau ** 2, axis=1)) * DT)


def compute_metrics(
    results: dict[str, dict[str, np.ndarray]]
) -> dict[str, dict[str, float]]:
    """Compute scalar performance metrics for a dict of simulation results."""
    step_start = np.searchsorted(TIME, 2.0)
    dist_start = np.searchsorted(TIME, 8.0)
    target_roll = np.deg2rad(20.0)
    metrics: dict[str, dict[str, float]] = {}

    for name, data in results.items():
        ax = per_axis_rms_deg(data["eta"], data["eta_ref"], dist_start)
        metrics[name] = {
            "step_settling_s":    settling_time(TIME, data["eta"][:, 0], target_roll, 2.0),
            "step_overshoot_pct": overshoot(data["eta"][:, 0], target_roll, step_start),
            "step_rms_deg":       rms_error_deg(data["eta"], data["eta_ref"], step_start),
            "dist_rms_deg":       rms_error_deg(data["eta"], data["eta_ref"], dist_start),
            "dist_max_deg":       max_error_deg(data["eta"], data["eta_ref"], dist_start),
            "dist_rms_roll":      ax[0],
            "dist_rms_pitch":     ax[1],
            "dist_rms_yaw":       ax[2],
            "control_var":        control_variation(data["u"]),
            "peak_cmd_rate":      peak_command_rate(data["u"]),
            "ist":                integrated_squared_torque(data["tau"]),
        }
    return metrics


# ── Sensitivity study ──────────────────────────────────────────────────────────
def run_sensitivity() -> dict:
    """Sweep observer filter time constant T_f and allocation mismatch δ.

    Returns a dict with two sub-dicts:
      tf_sweep    : dist_rms for proposed and SMC at each T_f value
      delta_sweep : dist_rms for proposed and SMC at each mismatch level
    """
    tf_values    = [0.02, 0.05, 0.10, 0.20]
    delta_values = [0.00, 0.05, 0.10, 0.20]
    dist_start   = np.searchsorted(TIME, 8.0)

    sens: dict = {"tf_sweep": {}, "delta_sweep": {}}

    for tf in tf_values:
        for ctrl in ("proposed", "smc"):
            r = simulate(ctrl, "disturbance", tf=tf, mismatch_pct=0.10,
                         rng=np.random.default_rng(42))
            key = str(tf)
            if key not in sens["tf_sweep"]:
                sens["tf_sweep"][key] = {}
            sens["tf_sweep"][key][f"{ctrl}_dist_rms"] = rms_error_deg(
                r["eta"], r["eta_ref"], dist_start
            )

    for delta in delta_values:
        for ctrl in ("proposed", "smc"):
            r = simulate(ctrl, "disturbance", tf=T_FILTER_DEFAULT,
                         mismatch_pct=delta, rng=np.random.default_rng(42))
            label = f"{int(delta * 100)}pct"
            if label not in sens["delta_sweep"]:
                sens["delta_sweep"][label] = {}
            sens["delta_sweep"][label][f"{ctrl}_dist_rms"] = rms_error_deg(
                r["eta"], r["eta_ref"], dist_start
            )

    return sens


# ── Multi-scenario + Monte Carlo generalization study ──────────────────────────
def run_generalization(n_mc: int = 40) -> dict:
    """Multi-scenario sweep and Monte Carlo robustness study.

    Parameters
    ----------
    n_mc : number of Monte Carlo runs (default 40; use 200 for extended study)

    Returns
    -------
    dict with:
      scenario_results     : {scenario: {controller: dist_rms}}
      scenario_disturbance : {scenario: {peak_disturbance_nm, peak_to_control_pct}}
      monte_carlo_runs     : {controller: [dist_rms per run]}
      monte_carlo_stats    : {controller: {mean, std, median, p95}}
    """
    dist_start = np.searchsorted(TIME, 8.0)

    # ── Multi-scenario sweep ──────────────────────────────────────────────────
    scenario_results: dict[str, dict[str, float]] = {}
    scenario_disturbance: dict[str, dict[str, float]] = {}

    for scenario in GENERALIZATION_SCENARIOS:
        scenario_results[scenario] = {}
        ref_run = simulate("proposed", "disturbance",
                           scenario=scenario, rng=np.random.default_rng(42))
        peak_dist = float(np.max(np.linalg.norm(ref_run["tau_dist"], axis=1)))
        scenario_disturbance[scenario] = {
            "peak_disturbance_nm":  peak_dist,
            "peak_to_control_pct": 100.0 * peak_dist / max_available_torque_norm(),
        }
        for ctrl in MONTE_CARLO_CONTROLLERS:
            r = simulate(ctrl, "disturbance",
                         scenario=scenario, rng=np.random.default_rng(42))
            scenario_results[scenario][ctrl] = rms_error_deg(
                r["eta"], r["eta_ref"], dist_start
            )

    # ── Monte Carlo ───────────────────────────────────────────────────────────
    mc_runs: dict[str, list[float]] = {k: [] for k in MONTE_CARLO_CONTROLLERS}

    for seed in range(100, 100 + n_mc):
        trial_rng    = np.random.default_rng(seed)
        initial_eta  = np.deg2rad(
            trial_rng.uniform(low=[-3.0, -2.0, -3.0], high=[3.0, 2.0, 3.0])
        )
        mismatch_pct = float(trial_rng.uniform(0.05, 0.20))
        tf           = float(trial_rng.choice([0.02, 0.05, 0.10, 0.20]))

        for ctrl in MONTE_CARLO_CONTROLLERS:
            r = simulate(
                ctrl, "disturbance",
                tf=tf, mismatch_pct=mismatch_pct,
                scenario="nominal",
                rng=np.random.default_rng(seed * 100 + len(mc_runs[ctrl])),
                initial_eta=initial_eta,
            )
            mc_runs[ctrl].append(
                rms_error_deg(r["eta"], r["eta_ref"], dist_start)
            )

    mc_stats: dict[str, dict[str, float]] = {}
    for ctrl, vals in mc_runs.items():
        arr = np.asarray(vals)
        mc_stats[ctrl] = {
            "mean":   float(np.mean(arr)),
            "std":    float(np.std(arr)),
            "median": float(np.median(arr)),
            "p95":    float(np.percentile(arr, 95)),
            "p99":    float(np.percentile(arr, 99)),
        }

    return {
        "scenario_results":     scenario_results,
        "scenario_disturbance": scenario_disturbance,
        "monte_carlo_runs":     mc_runs,
        "monte_carlo_stats":    mc_stats,
    }


def run_wilcoxon_tests(mc_runs: dict[str, list[float]]) -> dict:
    """Pairwise one-sided Wilcoxon rank-sum tests: proposed vs. each baseline.

    Requires scipy.  If scipy is unavailable, returns placeholder values.
    """
    if not _SCIPY_AVAILABLE:
        print("    [Warning] scipy not available; skipping Wilcoxon tests.")
        return {f"proposed_vs_{c}": {"p_value": float("nan"), "effect_r": float("nan")}
                for c in ["adrc", "smc", "lqr", "pid"]}

    results = {}
    proposed = np.asarray(mc_runs["proposed"])
    for ctrl in ["adrc", "smc", "lqr", "pid"]:
        baseline = np.asarray(mc_runs[ctrl])
        stat, p = sp_stats.mannwhitneyu(proposed, baseline, alternative="less")
        n1, n2 = len(proposed), len(baseline)
        r = 1.0 - 2.0 * stat / (n1 * n2)
        results[f"proposed_vs_{ctrl}"] = {"p_value": float(p), "effect_r": float(r)}
    return results
